server:
  port: 8082
spring:
  application:
    name: delivery
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  rabbitmq:
    host: ${RABBITMQ:localhost}
    port: 5672
    username: guest
    password: guest